function img = raw_combineME(name,save_path,datatype,echoes)
%readMEraw:     Read raw multi-echo files generated by writeMEraw or other
%               functions (like Pseries) of Russell Dibb's METoolKit
%
% dims          retrieved from a .mat file created another m-file
%
% Example:      test_img = readMEraw('test',pwd);

load dims;
if ~exist('name','var')
    name = '';
end
if ~exist('save_path','var')
    save_path = '';
else
    save_path = dir([save_path '*']);
    nruns = length(save_path);
end
if ~exist('datatype','var')
    datatype = 'short';
end
if ~exist('echoes','var')
    echoes = 1:dims(4);
end

img = single(zeros([dims(1:3) length(echoes)]));
kecho = 0;
dump = zeros(2,dims(1),nruns);
for k = echoes
    kecho = kecho+1;
    fprintf('   Summing echo %d/%d   - ',k,dims(4)); 
    echoname = [name '_' datatype '_echo_' num2str(k) '.raw'];
    back = 0; time = 0;
    for q = 1:nruns
        fid(q) = fopen(echoname);
    end          
        for z = 1:dims(3)
            [back,time] = progress(z,dims(3),'slice',back,time); % comment this line to eliminate progress countdown
            for y = 1:dims(2)
                for q = 1:nruns
                    dump(:,:,q) = fread(fid(q),[2 dims(1)], datatype);
                end
                dumpsum = mean(dump,3);
                img(:,y,z,kecho) = squeeze(dumpsum(2,1:end)+1i*dumpsum(1,:)); % make single here?
            end
        end
    
    fclose all;
    
end